version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: symphony
      POSTGRES_PASSWORD: symphony
      POSTGRES_DB: symphonydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
